name: help_scout_beacon_example
description: "Demonstrates how to use the help_scout_beacon plugin."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.0
  flutter: ^3.24.3

dependencies:
  flutter:
    sdk: flutter

  help_scout_beacon:
    path: ../

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
